### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MathieuBartels** [rdehaan/KRR-course-2020#1]
Shouldn't this be 

```python 
sudoku_possible_values = propagate(sudoku_possible_values,k);
 ```
Or did I misunderstand what propagate should do? 

https://github.com/rdehaan/KRR-course/blob/25af94afbe6e17ebc4ea0425c8029b8d3bebc405/hw1/sudoku.py#L319

**Comment by rdehaan** [comment]
Yes, you're right. I fixed it. Thanks! :)
